### ISSUE TITLE
Getting crushed from above removes 2 points

### ISSUE THREAD

**Issue by JXVD** [Juskelis/Champloo#145]
In Branch #142 
### Repro Steps
1. Start a game in crush
2. Get 3 points with one character
3. Go into the bottom part of the crusher
4. Get crushed

### Expected Functionality
The crushed player loses 1 point

### Actual Functionality
The crushed player loses 2 points

### Notes
If the player gets crushed from below as well, in the middle part of the crusher, they only lose 1 point

**Comment by Juskelis** [comment]
Crush gets called for each player for each obstacle that is crushing them. This means that when we get smooshed by a block from above, we are both trying to go down to avoid the block (crushing w/ floor) and trying to go up to avoid floor (crushing w/ ceiling) so we generate two crush events when the moving platform is coming from above. On the other hand, when smooshed into the ceiling by a moving platform, the platform overrides this default behavior, and forces the player to always avoid the platform, so only one crush event occurs for the ceiling. This is expected behavior, and is fine.

The bad part is that we were not checking for death when the player gets crushed; so multiple crushes were resulting in multiple "deaths." I tried to solve this by just checking for death in OnCrush before doing anything, but turns out the network code actually takes a frame to propagate, even on local. I ended up setting up a new variable to keep track of whether a death message was in flight from this character, and treating that as Dead too. PR will be up shortly.
